server:
  port: 9015

adapters:
  docker:
    docker-host: "unix:///var/run/docker.sock"
    registry-url: "ghcr.io"
    registry-username: "trodix"
    registry-token:
    registry-email: "sebastien.vallet89@gmail.com"
  springactuator:
    actuator-endpoints:
      - "http://localhost:8010/actuator"