server:
  port: 9015

adapters:
  docker:
    docker-host: "unix:///var/run/docker.sock"
  springactuator:
    actuator-endpoints:
      - "http://localhost:8010/actuator"
  http:
    http-endpoints:
      - "https://google.com"